name: Build Flutter APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      # Robot disuruh masuk ke folder Coding
      - run: flutter pub get
        working-directory: Coding
      - run: flutter build apk --release --target-platform android-arm64
        working-directory: Coding
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: DTX-Hum-Release
          path: Coding/build/app/outputs/flutter-apk/app-release.apk
